### ISSUE TITLE
C574 issues

### ISSUE THREAD

**Issue by a3020** [c5devlabs/concrete-twitter-feed-block#1]
There seems to be in issue in C574 when authorizing an account. It generated this error:

Class 'Concrete\Core\Routing\URL' not found (/Src/TwitterFeedRequestHandler.php)

**Comment by olsgreen** [comment]
Thanks for reporting, I'll take a look.

**Comment by a3020** [comment]
Have you had the chance yet to see what's going on?

**Comment by olsgreen** [comment]
Fixed in 0.9.11.
